data:
        "/datahome/snakemake_workflows/data/reads/Hospital_Duct3B_Tuft2A_100319"
results_loc:
        "/datahome/snakemake_workflows/hosp_100319"
condition:
        Tuft:
                Tuft3A,Tuft3B
        Duct:
                Duct3A,Duct3B
threads:
        "10"
ref:
  "/datahome/snakemake_workflows/data/ref/gencode/mus_musculus/GRCm38.primary_assembly.genome.fa"
index:
  "/datahome/snakemake_workflows/data/salmon_decoy/mus_musculus/gencode_mus_musculus_index"
gtf:
  "/datahome/snakemake_workflows/data/GTFs/mus_musculus/gencode.vM22.annotation.gtf.gz"
vcf:
  "/datahome/snakemake_workflows/data/vcf/mus_musculus/mouse_dbsnp_reheader.vcf.gz"
gzipped_reads:
  "True"
